#!/usr/bin/env bash

set -e
# INSTALLDIR must be an absolute path to the install location
#INSTALLDIR=@@INSTALLDIR@@

BASHLIB="`find ${INSTALLDIR:-$PWD} -type d | grep -E '/(bin|lib)$' | xargs -n1 printf "%s:"`"
PATH="$BASHLIB:$PATH"

source bash+ :std
